---
- name: check if undercloud guest exists
  command: >-
    virsh domuuid {{ undercloud_name }}
  environment:
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"
  register: guest_exists
  failed_when: false
  changed_when: guest_exists.rc != 0

- name: create the undercloud
  when: guest_exists is changed
  command: >-
    virt-install
    -n {{ undercloud_name }}
    --cpu host-passthrough
    --vcpus {{ undercloud_vcpus }}
    --memory memory={{ undercloud_ram }}
    --disk path={{ undercloud_image_path }} --import
    --os-variant rhel7.7 --noautoconsole
    -w network=default
    -w bridge={{ openstack_switch }},virtualport_type=openvswitch,portgroup=internal
  environment:
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

- name: wait for the undercloud to boot
  register: agent_check
  until: agent_check.rc == 0
  delay: 5
  retries: 12
  changed_when: false
  command: >-
    virsh -c qemu:///system
    qemu-agent-command {{ undercloud_name }} '{"execute": "guest-ping"}'
  environment:
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"
