---
- name: prepare virthost
  hosts: virthost
  tags: [always]
  tasks:
    - name: ensure work directory is defined
      set_fact:
        osp_demo_workdir: "{{ ansible_env.HOME }}/director-install-tmp"
      when: osp_demo_workdir is not defined

    - name: ensure work directory exists
      file:
        path: "{{ osp_demo_workdir }}"
        state: directory

- name: prepare undercloud guest
  tags: [prepare]
  hosts: virthost
  gather_facts: false
  tasks:
    - name: configure libvirt
      include_role:
        name: libvirt
    - name: configure undercloud image
      include_role:
        name: undercloud_image
    - name: create undercloud guest
      include_role:
        name: undercloud_guest
    - name: give inventory time to settle
      pause:
        seconds: 5

- name: refresh inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - meta: refresh_inventory

- hosts: undercloud
  name: configure undercloud
  tasks:
    - name: basic undercloud configuration
      tags: [config]
      include_role:
        name: undercloud_config

    - name: register undercloud
      tags: [register, extended]
      include_role:
        name: undercloud_register

    - name: ensure a functional version of podman is installed
      tags: [bugs]
      include_role:
        name: podman

    - name: prepare stack user
      include_role:
        name: stack_user

    - name: prepare undercloud install
      include_role:
        name: undercloud_install_prep

- name: install the undercloud
  hosts: undercloud
  become: true
  become_user: stack
  when: install_undercloud|default(false)
  tasks:
    - name: install undercloud
      command: >-
        openstack undercloud install
