---
- name: check if openstack switch exists
  become: true
  command: >-
    ovs-vsctl br-exists {{ openstack_switch }}
  register: switch_exists
  failed_when: false
  changed_when: switch_exists.rc != 0

- name: create undercloud switch
  become: true
  when: switch_exists is changed
  command: >-
    ovs-vsctl add-br {{ openstack_switch }}

- name: create interface config files
  template:
    src: ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item.name }}"
  vars:
    device: "{{ item.name }}"
    address: "{{ item.cidr|nthhost(1) }}"
    prefix: "{{ item.cidr|ipaddr('prefix') }}"
    type: OVSIntPort
    devicetype: ovs
    ovs_options: "tag={{ item.tag }}"
    ovs_bridge: "{{ openstack_switch }}"
  register: interface_config
  loop:
    - name: extgw
      tag: 200
      cidr: "{{ external_network_cidr }}"
    - name: floatgw
      tag: 201
      cidr: "{{ floating_network_cidr }}"

- name: bring up interfaces
  shell: |
    ifdown {{ item.item.name }}
    sleep 1
    ifup {{ item.item.name }}
  when: item is changed
  loop: "{{ interface_config.results }}"

- name: ensure masquerade rules exist
  shell: |
    gwdev=$(ip route | awk '$1 == "default" {print $5}')
    rule="
      -s {{ item }}
      -o $gwdev
      -j MASQUERADE
    "
    if ! iptables -t nat -C POSTROUTING $rule; then
      iptables -t nat -A POSTROUTING $rule
    fi
  loop:
    - "{{ external_network_cidr }}"
    - "{{ floating_network_cidr }}"

- name: check if openstack network exists
  command: >-
    virsh net-info openstack
  register: libvirt_net
  failed_when: false
  changed_when: libvirt_net.rc != 0
  environment:
    LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

- name: create openstack network
  when: libvirt_net is changed
  block:
    - name: copy network definition to virthost
      copy:
        src: openstack_network.xml
        dest: "{{ osp_demo_workdir }}/openstack_network.xml"

    - name: define openstack network
      command: >-
        virsh net-define "{{ osp_demo_workdir }}/openstack_network.xml"
      environment:
        LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

    - name: start openstack network
      command: >-
        virsh net-start openstack
      environment:
        LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"

    - name: autostart openstack network
      command:
        virsh net-autostart openstack
      environment:
        LIBVIRT_DEFAULT_URI: "{{ libvirt_uri }}"
