---
parameter_defaults:
  ExtraConfig:
    tripleo::firewall::firewall_rules:
      '050 allow ssh from virthost':
        port: 22
        proto: tcp
        action: accept

  # allow redeploy to update network configuration
  NetworkDeploymentActions: ['CREATE', 'UPDATE']
