---
resource_registry:
  OS::TripleO::Network::Storage: OS::Heat::None
  OS::TripleO::Network::StorageMgmt: OS::Heat::None

parameter_defaults:
  ExtraConfig:
    tripleo::firewall::firewall_rules:
      '050 allow ssh from virthost':
        port: 22
        proto: tcp
        action: accept

  # allow redeploy to update network configuration
  #NetworkDeploymentActions: ['CREATE', 'UPDATE']
