---
- name: get podman version
  command: >-
    rpm -q podman --qf '%{VERSION}\n%{RELEASE}\n'
  args:
    warn: false
  failed_when: false
  register: podman_version

- name: install appropriate version of podman
  when: >-
    podman_version.rc != 0 or
    (podman_version.stdout_lines[0] == '1.4.2' and
    podman_version.stdout_lines[1]|int <= 5)
  tags: [bugs]
  block:
    - name: copy packages to target
      copy:
        src: "{{ item }}"
        dest: "."
      loop: "{{ podman_packages }}"

    - name: install packages
      command: >-
        yum -y localinstall
        {% for pkg in podman_packages %}
        {{ pkg }}
        {% endfor %}
      args:
        warn: false
