---
- set_fact:
    root_device: vda
  when: '"vda" in ansible_devices'

- set_fact:
    root_device: sda
  when: '"sda" in ansible_devices'

- fail:
    msg: No root device
  when: root_device is not defined

- name: resize {{ root_device }}
  command: >-
    growpart /dev/{{ root_device }} 1
  vars:
    part: >-
      {{ ansible_devices[root_device].partitions['%s1' % root_device] }}
  when: (part.sectors|int * part.sectorsize|int) / (1024*1024) < 20000
  register: part_resize

- name: resize root fs
  command: >-
    xfs_growfs /
  when: part_resize is changed

- name: set hostname
  command: >-
    hostnamectl set-hostname {{ undercloud_hostname }}

- name: ensure hosts entry for undercloud
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ undercloud_hostname }}"
