---
- name: check if overlcoud image exists in glance
  become: true
  become_user: stack
  shell: |-
    . $HOME/stackrc
    openstack image show overcloud-full
  register: image_check
  failed_when: false
  changed_when: image_check.rc != 0

- name: get overcloud images
  when: image_check is changed
  block:
    - name: fetch overcloud image packages
      package:
        state: installed
        name: "{{ overcloud_image_packages }}"

    - name: unpack overcloud images
      become: true
      become_user: stack
      shell: |-
        mkdir -p $HOME/images
        tar -C $HOME/images \
        -xf {{ item }}
      args:
        warn: false
      loop: "{{ overcloud_image_tarballs }}"

    - name: upload images to glance
      become: true
      become_user: stack
      shell: |-
        . $HOME/stackrc
        openstack overcloud image upload --image-path /home/stack/images/
